name: Cppcheck


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
jobs:

  build:
   
    runs-on: ubuntu-latest

    
    steps:
     
      - uses: actions/checkout@v2

      
      - name: Install
        run: Sudo apt-get install cppcheck

      
      - name: voting_management_system
        run: cppcheck --enable-all 3_Implementation
